CREATE TABLE hrm.employee_schedule (
    id uuid NOT NULL,
    employee uuid NOT NULL,
    date_time_start timestamp,
    date_time_end timestamp,
    is_rest_day bool,
    is_overtime bool,
    deleted bool,
    created_by varchar(50),
    created_date timestamp DEFAULT now(),
    last_modified_by varchar(50),
    last_modified_date timestamp DEFAULT now(),
    meal_break_start timestamp,
    meal_break_end timestamp,
    label varchar(255),
    title varchar(255),
    locked bool,
    color varchar(255),
    department uuid,
    is_custom bool,
    is_leave bool,
    request uuid,
    with_pay bool NOT NULL DEFAULT true,
    company uuid not null,
    PRIMARY KEY (id)
);
